//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        internal static string LoginPage_backButton {
            get {
                return ResourceManager.GetString("LoginPage_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékesítői azonosítás.
        /// </summary>
        internal static string LoginPage_cashierTitle {
            get {
                return ResourceManager.GetString("LoginPage_cashierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérjük, töltse ki a mezőt!.
        /// </summary>
        internal static string LoginPage_errorEmpty {
            get {
                return ResourceManager.GetString("LoginPage_errorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        internal static string LoginPage_identifierLabel {
            get {
                return ResourceManager.GetString("LoginPage_identifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg az azonosítóját.
        /// </summary>
        internal static string LoginPage_identifierPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_identifierPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belépés.
        /// </summary>
        internal static string LoginPage_loginButton {
            get {
                return ResourceManager.GetString("LoginPage_loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        internal static string LoginPage_passwordLabel {
            get {
                return ResourceManager.GetString("LoginPage_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg a jelszavát.
        /// </summary>
        internal static string LoginPage_passwordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_passwordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktári belépés.
        /// </summary>
        internal static string LoginPage_storageTitle {
            get {
                return ResourceManager.GetString("LoginPage_storageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékesítési felület.
        /// </summary>
        internal static string WelcomeSelector_cashierBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_cashierBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to English.
        /// </summary>
        internal static string WelcomeSelector_languageBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_languageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktárkezelési felület.
        /// </summary>
        internal static string WelcomeSelector_storageBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_storageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük az üzletkezelő rendszerben!.
        /// </summary>
        internal static string WelcomeSelector_welcome {
            get {
                return ResourceManager.GetString("WelcomeSelector_welcome", resourceCulture);
            }
        }
    }
}
