//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Vissza.
        /// </summary>
        internal static string CashierPage_backButton {
            get {
                return ResourceManager.GetString("CashierPage_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Kosár törlése.
        /// </summary>
        internal static string CashierPage_clearCartButton {
            get {
                return ResourceManager.GetString("CashierPage_clearCartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törli a kosár tartalmát?.
        /// </summary>
        internal static string CashierPage_clearCartConfirmation {
            get {
                return ResourceManager.GetString("CashierPage_clearCartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megerősítés.
        /// </summary>
        internal static string CashierPage_confirmationTitle {
            get {
                return ResourceManager.GetString("CashierPage_confirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ft.
        /// </summary>
        internal static string CashierPage_currency {
            get {
                return ResourceManager.GetString("CashierPage_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdj el termékeket hozzáadni!.
        /// </summary>
        internal static string CashierPage_emptyCartMessage {
            get {
                return ResourceManager.GetString("CashierPage_emptyCartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kosár üres.
        /// </summary>
        internal static string CashierPage_emptyCartTitle {
            get {
                return ResourceManager.GetString("CashierPage_emptyCartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kosár üres!.
        /// </summary>
        internal static string CashierPage_emptyCartWarning {
            get {
                return ResourceManager.GetString("CashierPage_emptyCartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string CashierPage_errorTitle {
            get {
                return ResourceManager.GetString("CashierPage_errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem elegendő összeg!
        ///
        ///Fizetendő: {0} Ft
        ///Kapott: {1} Ft
        ///Hiányzik: {2} Ft.
        /// </summary>
        internal static string CashierPage_insufficientAmount {
            get {
                return ResourceManager.GetString("CashierPage_insufficientAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tételek száma:.
        /// </summary>
        internal static string CashierPage_itemCountLabel {
            get {
                return ResourceManager.GetString("CashierPage_itemCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a termékek betöltése közben: {0}.
        /// </summary>
        internal static string CashierPage_loadProductsError {
            get {
                return ResourceManager.GetString("CashierPage_loadProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💳 Fizetés.
        /// </summary>
        internal static string CashierPage_payButton {
            get {
                return ResourceManager.GetString("CashierPage_payButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetendő összeg: {0} Ft
        ///Kapott összeg: {1} Ft
        ///Visszajáró: {2} Ft
        ///
        ///Biztosan véglegesíti a tranzakciót?.
        /// </summary>
        internal static string CashierPage_paymentConfirmation {
            get {
                return ResourceManager.GetString("CashierPage_paymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetés megerősítése.
        /// </summary>
        internal static string CashierPage_paymentConfirmationTitle {
            get {
                return ResourceManager.GetString("CashierPage_paymentConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetés sikeres!
        ///
        ///Végösszeg: {0} Ft
        ///Kapott: {1} Ft
        ///Visszajáró: {2} Ft.
        /// </summary>
        internal static string CashierPage_paymentSuccess {
            get {
                return ResourceManager.GetString("CashierPage_paymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék.
        /// </summary>
        internal static string CashierPage_productColumn {
            get {
                return ResourceManager.GetString("CashierPage_productColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék nem található!.
        /// </summary>
        internal static string CashierPage_productNotFound {
            get {
                return ResourceManager.GetString("CashierPage_productNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyiség.
        /// </summary>
        internal static string CashierPage_quantityColumn {
            get {
                return ResourceManager.GetString("CashierPage_quantityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapott összeg.
        /// </summary>
        internal static string CashierPage_receivedAmountLabel {
            get {
                return ResourceManager.GetString("CashierPage_receivedAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        internal static string CashierPage_searchButton {
            get {
                return ResourceManager.GetString("CashierPage_searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Vonalkód, cikkszám vagy termék név keresése....
        /// </summary>
        internal static string CashierPage_searchPlaceholder {
            get {
                return ResourceManager.GetString("CashierPage_searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres tranzakció.
        /// </summary>
        internal static string CashierPage_successTitle {
            get {
                return ResourceManager.GetString("CashierPage_successTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénztár.
        /// </summary>
        internal static string CashierPage_title {
            get {
                return ResourceManager.GetString("CashierPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összeg.
        /// </summary>
        internal static string CashierPage_totalColumn {
            get {
                return ResourceManager.GetString("CashierPage_totalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végösszeg.
        /// </summary>
        internal static string CashierPage_totalLabel {
            get {
                return ResourceManager.GetString("CashierPage_totalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egységár.
        /// </summary>
        internal static string CashierPage_unitPriceColumn {
            get {
                return ResourceManager.GetString("CashierPage_unitPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÁFA tartalom:.
        /// </summary>
        internal static string CashierPage_vatLabel {
            get {
                return ResourceManager.GetString("CashierPage_vatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        internal static string CashierPage_warningTitle {
            get {
                return ResourceManager.GetString("CashierPage_warningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        internal static string LoginPage_backButton {
            get {
                return ResourceManager.GetString("LoginPage_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékesítői azonosítás.
        /// </summary>
        internal static string LoginPage_cashierTitle {
            get {
                return ResourceManager.GetString("LoginPage_cashierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérjük, töltse ki a mezőt!.
        /// </summary>
        internal static string LoginPage_errorEmpty {
            get {
                return ResourceManager.GetString("LoginPage_errorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        internal static string LoginPage_identifierLabel {
            get {
                return ResourceManager.GetString("LoginPage_identifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg az azonosítóját.
        /// </summary>
        internal static string LoginPage_identifierPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_identifierPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belépés.
        /// </summary>
        internal static string LoginPage_loginButton {
            get {
                return ResourceManager.GetString("LoginPage_loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        internal static string LoginPage_passwordLabel {
            get {
                return ResourceManager.GetString("LoginPage_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg a jelszavát.
        /// </summary>
        internal static string LoginPage_passwordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_passwordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktári belépés.
        /// </summary>
        internal static string LoginPage_storageTitle {
            get {
                return ResourceManager.GetString("LoginPage_storageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékesítési felület.
        /// </summary>
        internal static string WelcomeSelector_cashierBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_cashierBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to English.
        /// </summary>
        internal static string WelcomeSelector_languageBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_languageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktárkezelési felület.
        /// </summary>
        internal static string WelcomeSelector_storageBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_storageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük az üzletkezelő rendszerben!.
        /// </summary>
        internal static string WelcomeSelector_welcome {
            get {
                return ResourceManager.GetString("WelcomeSelector_welcome", resourceCulture);
            }
        }
    }
}
