//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Vissza.
        /// </summary>
        internal static string CashierPage_backButton {
            get {
                return ResourceManager.GetString("CashierPage_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Kosár törlése.
        /// </summary>
        internal static string CashierPage_clearCartButton {
            get {
                return ResourceManager.GetString("CashierPage_clearCartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törli a kosár tartalmát?.
        /// </summary>
        internal static string CashierPage_clearCartConfirmation {
            get {
                return ResourceManager.GetString("CashierPage_clearCartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megerősítés.
        /// </summary>
        internal static string CashierPage_confirmationTitle {
            get {
                return ResourceManager.GetString("CashierPage_confirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ft.
        /// </summary>
        internal static string CashierPage_currency {
            get {
                return ResourceManager.GetString("CashierPage_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdj el termékeket hozzáadni!.
        /// </summary>
        internal static string CashierPage_emptyCartMessage {
            get {
                return ResourceManager.GetString("CashierPage_emptyCartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kosár üres.
        /// </summary>
        internal static string CashierPage_emptyCartTitle {
            get {
                return ResourceManager.GetString("CashierPage_emptyCartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kosár üres!.
        /// </summary>
        internal static string CashierPage_emptyCartWarning {
            get {
                return ResourceManager.GetString("CashierPage_emptyCartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string CashierPage_errorTitle {
            get {
                return ResourceManager.GetString("CashierPage_errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem elegendő összeg!
        ///
        ///Fizetendő: {0} Ft
        ///Kapott: {1} Ft
        ///Hiányzik: {2} Ft.
        /// </summary>
        internal static string CashierPage_insufficientAmount {
            get {
                return ResourceManager.GetString("CashierPage_insufficientAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tételek száma:.
        /// </summary>
        internal static string CashierPage_itemCountLabel {
            get {
                return ResourceManager.GetString("CashierPage_itemCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a termékek betöltése közben: {0}.
        /// </summary>
        internal static string CashierPage_loadProductsError {
            get {
                return ResourceManager.GetString("CashierPage_loadProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💳 Fizetés.
        /// </summary>
        internal static string CashierPage_payButton {
            get {
                return ResourceManager.GetString("CashierPage_payButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetendő összeg: {0} Ft
        ///Kapott összeg: {1} Ft
        ///Visszajáró: {2} Ft
        ///
        ///Biztosan véglegesíti a tranzakciót?.
        /// </summary>
        internal static string CashierPage_paymentConfirmation {
            get {
                return ResourceManager.GetString("CashierPage_paymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetés megerősítése.
        /// </summary>
        internal static string CashierPage_paymentConfirmationTitle {
            get {
                return ResourceManager.GetString("CashierPage_paymentConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizetés sikeres!
        ///
        ///Végösszeg: {0} Ft
        ///Kapott: {1} Ft
        ///Visszajáró: {2} Ft.
        /// </summary>
        internal static string CashierPage_paymentSuccess {
            get {
                return ResourceManager.GetString("CashierPage_paymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék.
        /// </summary>
        internal static string CashierPage_productColumn {
            get {
                return ResourceManager.GetString("CashierPage_productColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék nem található!.
        /// </summary>
        internal static string CashierPage_productNotFound {
            get {
                return ResourceManager.GetString("CashierPage_productNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyiség.
        /// </summary>
        internal static string CashierPage_quantityColumn {
            get {
                return ResourceManager.GetString("CashierPage_quantityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapott összeg.
        /// </summary>
        internal static string CashierPage_receivedAmountLabel {
            get {
                return ResourceManager.GetString("CashierPage_receivedAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        internal static string CashierPage_searchButton {
            get {
                return ResourceManager.GetString("CashierPage_searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Vonalkód, cikkszám vagy termék név keresése....
        /// </summary>
        internal static string CashierPage_searchPlaceholder {
            get {
                return ResourceManager.GetString("CashierPage_searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres tranzakció.
        /// </summary>
        internal static string CashierPage_successTitle {
            get {
                return ResourceManager.GetString("CashierPage_successTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénztár.
        /// </summary>
        internal static string CashierPage_title {
            get {
                return ResourceManager.GetString("CashierPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összeg.
        /// </summary>
        internal static string CashierPage_totalColumn {
            get {
                return ResourceManager.GetString("CashierPage_totalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végösszeg.
        /// </summary>
        internal static string CashierPage_totalLabel {
            get {
                return ResourceManager.GetString("CashierPage_totalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egységár.
        /// </summary>
        internal static string CashierPage_unitPriceColumn {
            get {
                return ResourceManager.GetString("CashierPage_unitPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÁFA tartalom:.
        /// </summary>
        internal static string CashierPage_vatLabel {
            get {
                return ResourceManager.GetString("CashierPage_vatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        internal static string CashierPage_warningTitle {
            get {
                return ResourceManager.GetString("CashierPage_warningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        internal static string LoginPage_backButton {
            get {
                return ResourceManager.GetString("LoginPage_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékesítői azonosítás.
        /// </summary>
        internal static string LoginPage_cashierTitle {
            get {
                return ResourceManager.GetString("LoginPage_cashierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérjük, töltse ki a mezőt!.
        /// </summary>
        internal static string LoginPage_errorEmpty {
            get {
                return ResourceManager.GetString("LoginPage_errorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás felhasználó.
        /// </summary>
        internal static string LoginPage_errorInvalidUser {
            get {
                return ResourceManager.GetString("LoginPage_errorInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a felhasználó nem érheti el a raktár felületet.
        /// </summary>
        internal static string LoginPage_errorNoStorageAccess {
            get {
                return ResourceManager.GetString("LoginPage_errorNoStorageAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string LoginPage_errorTitle {
            get {
                return ResourceManager.GetString("LoginPage_errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehhez a felhasználóhoz nem ez a jelszó tartozik.
        /// </summary>
        internal static string LoginPage_errorWrongPassword {
            get {
                return ResourceManager.GetString("LoginPage_errorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        internal static string LoginPage_identifierLabel {
            get {
                return ResourceManager.GetString("LoginPage_identifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg az azonosítóját.
        /// </summary>
        internal static string LoginPage_identifierPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_identifierPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belépés.
        /// </summary>
        internal static string LoginPage_loginButton {
            get {
                return ResourceManager.GetString("LoginPage_loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        internal static string LoginPage_passwordLabel {
            get {
                return ResourceManager.GetString("LoginPage_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adja meg a jelszavát.
        /// </summary>
        internal static string LoginPage_passwordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_passwordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktári belépés.
        /// </summary>
        internal static string LoginPage_storageTitle {
            get {
                return ResourceManager.GetString("LoginPage_storageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        internal static string MessageBox_buttonCancel {
            get {
                return ResourceManager.GetString("MessageBox_buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        internal static string MessageBox_buttonNo {
            get {
                return ResourceManager.GetString("MessageBox_buttonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MessageBox_buttonOK {
            get {
                return ResourceManager.GetString("MessageBox_buttonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen.
        /// </summary>
        internal static string MessageBox_buttonYes {
            get {
                return ResourceManager.GetString("MessageBox_buttonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Műveletek.
        /// </summary>
        internal static string StoragePage_actionsColumn {
            get {
                return ResourceManager.GetString("StoragePage_actionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Új termék.
        /// </summary>
        internal static string StoragePage_addNewButton {
            get {
                return ResourceManager.GetString("StoragePage_addNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Vissza.
        /// </summary>
        internal static string StoragePage_backButton {
            get {
                return ResourceManager.GetString("StoragePage_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        internal static string StoragePage_cancelButton {
            get {
                return ResourceManager.GetString("StoragePage_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megerősítés.
        /// </summary>
        internal static string StoragePage_confirmationTitle {
            get {
                return ResourceManager.GetString("StoragePage_confirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törli ezt a terméket: {0}?.
        /// </summary>
        internal static string StoragePage_deleteConfirmation {
            get {
                return ResourceManager.GetString("StoragePage_deleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a törlés során: {0}.
        /// </summary>
        internal static string StoragePage_deleteError {
            get {
                return ResourceManager.GetString("StoragePage_deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A törlés funkció még nem került implementálásra..
        /// </summary>
        internal static string StoragePage_deleteNotImplemented {
            get {
                return ResourceManager.GetString("StoragePage_deleteNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék sikeresen törölve!.
        /// </summary>
        internal static string StoragePage_deleteSuccess {
            get {
                return ResourceManager.GetString("StoragePage_deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        internal static string StoragePage_deleteTooltip {
            get {
                return ResourceManager.GetString("StoragePage_deleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék adatok.
        /// </summary>
        internal static string StoragePage_editPanelTitle {
            get {
                return ResourceManager.GetString("StoragePage_editPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerkesztés.
        /// </summary>
        internal static string StoragePage_editTooltip {
            get {
                return ResourceManager.GetString("StoragePage_editTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbálj más keresési feltételeket használni!.
        /// </summary>
        internal static string StoragePage_emptyListMessage {
            get {
                return ResourceManager.GetString("StoragePage_emptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs találat.
        /// </summary>
        internal static string StoragePage_emptyListTitle {
            get {
                return ResourceManager.GetString("StoragePage_emptyListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string StoragePage_errorTitle {
            get {
                return ResourceManager.GetString("StoragePage_errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törtegység.
        /// </summary>
        internal static string StoragePage_fractionableLabel {
            get {
                return ResourceManager.GetString("StoragePage_fractionableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikkszám.
        /// </summary>
        internal static string StoragePage_idColumn {
            get {
                return ResourceManager.GetString("StoragePage_idColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen ár érték!.
        /// </summary>
        internal static string StoragePage_invalidPrice {
            get {
                return ResourceManager.GetString("StoragePage_invalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen készlet érték!.
        /// </summary>
        internal static string StoragePage_invalidStock {
            get {
                return ResourceManager.GetString("StoragePage_invalidStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen ÁFA érték!.
        /// </summary>
        internal static string StoragePage_invalidVat {
            get {
                return ResourceManager.GetString("StoragePage_invalidVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a termékek betöltése közben: {0}.
        /// </summary>
        internal static string StoragePage_loadProductsError {
            get {
                return ResourceManager.GetString("StoragePage_loadProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megnevezés.
        /// </summary>
        internal static string StoragePage_nameColumn {
            get {
                return ResourceManager.GetString("StoragePage_nameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megnevezés mező kötelező!.
        /// </summary>
        internal static string StoragePage_nameRequired {
            get {
                return ResourceManager.GetString("StoragePage_nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (új termék).
        /// </summary>
        internal static string StoragePage_newProductId {
            get {
                return ResourceManager.GetString("StoragePage_newProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikkszám.
        /// </summary>
        internal static string StoragePage_productIdLabel {
            get {
                return ResourceManager.GetString("StoragePage_productIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megnevezés*.
        /// </summary>
        internal static string StoragePage_productNameLabel {
            get {
                return ResourceManager.GetString("StoragePage_productNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eladási ár.
        /// </summary>
        internal static string StoragePage_salePriceColumn {
            get {
                return ResourceManager.GetString("StoragePage_salePriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eladási ár.
        /// </summary>
        internal static string StoragePage_salePriceLabel {
            get {
                return ResourceManager.GetString("StoragePage_salePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Mentés.
        /// </summary>
        internal static string StoragePage_saveButton {
            get {
                return ResourceManager.GetString("StoragePage_saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a mentés során: {0}.
        /// </summary>
        internal static string StoragePage_saveError {
            get {
                return ResourceManager.GetString("StoragePage_saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék sikeresen mentve!.
        /// </summary>
        internal static string StoragePage_saveSuccess {
            get {
                return ResourceManager.GetString("StoragePage_saveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        internal static string StoragePage_searchButton {
            get {
                return ResourceManager.GetString("StoragePage_searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Cikkszám vagy termék név keresése....
        /// </summary>
        internal static string StoragePage_searchPlaceholder {
            get {
                return ResourceManager.GetString("StoragePage_searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Készlet.
        /// </summary>
        internal static string StoragePage_stockColumn {
            get {
                return ResourceManager.GetString("StoragePage_stockColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Készlet.
        /// </summary>
        internal static string StoragePage_stockLabel {
            get {
                return ResourceManager.GetString("StoragePage_stockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres művelet.
        /// </summary>
        internal static string StoragePage_successTitle {
            get {
                return ResourceManager.GetString("StoragePage_successTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beszerzési ár.
        /// </summary>
        internal static string StoragePage_supplierPriceColumn {
            get {
                return ResourceManager.GetString("StoragePage_supplierPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beszerzési ár.
        /// </summary>
        internal static string StoragePage_supplierPriceLabel {
            get {
                return ResourceManager.GetString("StoragePage_supplierPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktárkezelés.
        /// </summary>
        internal static string StoragePage_title {
            get {
                return ResourceManager.GetString("StoragePage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egység.
        /// </summary>
        internal static string StoragePage_unitColumn {
            get {
                return ResourceManager.GetString("StoragePage_unitColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egység.
        /// </summary>
        internal static string StoragePage_unitLabel {
            get {
                return ResourceManager.GetString("StoragePage_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÁFA %.
        /// </summary>
        internal static string StoragePage_vatPercentageLabel {
            get {
                return ResourceManager.GetString("StoragePage_vatPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        internal static string StoragePage_warningTitle {
            get {
                return ResourceManager.GetString("StoragePage_warningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékesítési felület.
        /// </summary>
        internal static string WelcomeSelector_cashierBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_cashierBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to English.
        /// </summary>
        internal static string WelcomeSelector_languageBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_languageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktárkezelési felület.
        /// </summary>
        internal static string WelcomeSelector_storageBtn {
            get {
                return ResourceManager.GetString("WelcomeSelector_storageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük az üzletkezelő rendszerben!.
        /// </summary>
        internal static string WelcomeSelector_welcome {
            get {
                return ResourceManager.GetString("WelcomeSelector_welcome", resourceCulture);
            }
        }
    }
}
